# Generated by Django 6.0.5 on 2026-05-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Введите номер телефона', max_length=100, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, help_text='Введите город', null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, help_text='Введите город', null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото собаки', null=True, upload_to='image/', verbose_name='Фото'),
        ),
    ]
