# Generated by Django 6.0.5 on 2026-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contactinfo_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, help_text='Введите адрес', null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия'),
        ),
    ]
