# Generated by Django 6.0.5 on 2026-05-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_contactinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, help_text='Введите адрес', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(blank=True, help_text='Введите город', max_length=200, null=True, verbose_name='Город'),
        ),
    ]
