# Generated by Django 6.0.5 on 2026-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_contactinfo_address_alter_contactinfo_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото товара', null=True, upload_to='image/', verbose_name='Фото'),
        ),
    ]
